### ISSUE TITLE
org.freedesktop.Platform.GL.nvidia runtime is not automatically installed

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/ws.openarena.OpenArena#1]
The org.freedesktop.Platform.GL.nvidia runtime is not automatically installed when using GNOME Software to install the game. Can be fixed by manually running „_flatpak update_“ after the installation.

**Comment by TingPing** [comment]
This is an issue to report to either flatpak or gnome-software, though I suspect you are on an older release as I think I remember this being fixed not long ago.

**Comment by AsciiWolf** [comment]
I have the latest Fedora 26 release (GNOME Software 3.24.3, Flatpak 0.9.7).

**Comment by AsciiWolf** [comment]
Upstream bug report: https://bugzilla.gnome.org/show_bug.cgi?id=788363

**Comment by AsciiWolf** [comment]
Still not fixed. @TingPing Could you (or anyone else) please test this bug using a reproducer I have posted in the upstream bug report? Thanks!

**Comment by AsciiWolf** [comment]
This issue was fixed in the GNOME Software master.
