### ISSUE TITLE
2 OpenArenas at flathub

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/ws.openarena.OpenArena#13]
Hi,

currently you can find two OpenArenas ( OpenArena (Quake3e) and OpenArena ) at Flathub which look almost identical. Could you get in contact with [https://github.com/flathub/io.github.ec_.Quake3e.OpenArena](https://github.com/flathub/io.github.ec_.Quake3e.OpenArena)  to sync the two manifests in order to provide only one OpenArena at flathub? This would help avoid any confusion for potential users.

Regards
Jakob

**Comment by AsciiWolf** [comment]
Thanks for your ticket! It could be an interesting idea, however io.github.ec_.Quake3e.OpenArena as far as I know is actually a fork of OpenArena while this Flatpak is the original one (including the original engine version, assets etc.).

**Comment by AsciiWolf** [comment]
I see that you created the same ticket here: https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/issues/53
