### ISSUE TITLE
Please allow joystick support for this game!

### ISSUE THREAD

**Issue by Nokia808** [flathub/ws.openarena.OpenArena#6]
Hi. I'm new user for flatpak. I'm on Fedora 28 X64 bit Cinnamon edition, xorg system.

I installed open arena & it working very well apart from one thing essential which make it useless for many gamers: there is no support for joystick ! It is due to sandbox profile for this game ! This should be corrected because this game by itself allow for joystick.

**Comment by AsciiWolf** [comment]
Hi, thanks for your report. I think it would require `--device=all` permission to be added. I am not sure if I want something like this. However, you can easily override the default permissions, see [this](http://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override) man page.

**Comment by TingPing** [comment]
@AsciiWolf 	Just add it, its relatively harmless compared to things like file access.

**Comment by Nokia808** [comment]
@AsciiWolf 
Dear due you mean the following command:
$ flatpak override --device=all ws.openarena.OpenArena

**Comment by AsciiWolf** [comment]
@Nokia808 Yeah, that should permanently add the `--devices=all` permission to your ws.openarena.OpenArena installation.

**Comment by Nokia808** [comment]
@AsciiWolf 
O.K I did it & it worked. But dear the command not working on my system as a regular user ($). But it only worked when I run it as a root user (#). In fact I use sudo.

Only one question (last question): though it is not related to this thread but I have no other place to ask about it. Dear, my laptop is switchable system with 2 VGA (built-in & dedicated). By default any program run only using built-in VGA. To make it run using dedicated VGA + built-in VGA I have to change command in it's icon that created in my application menu by add the following to it's start:

env DRI_PRIME=1

for example:

env DRI_PRIME=1 firefox

Just I would like you to issuer me is this also applied for flatpak application or not ?

For example Open Arena command as a flatpak in it's icon in my application menu is:

/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=openarena ws.openarena.OpenArena

so to run it with my dedicated VGA is the following correct:

env DRI_PRIME=1 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=openarena ws.openarena.OpenArena

& thank you very much for your kind help !

**Comment by AsciiWolf** [comment]
@Nokia808 I don't have any experience with switchable GPUs, but this could work:
`/usr/bin/flatpak run --env=DRI_PRIME=1 --branch=stable --arch=x86_64 --command=openarena ws.openarena.OpenArena`

**Comment by AsciiWolf** [comment]
Feel free to send a PR for the joystick support. :)
